---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: socketio
  namespace: common-staging
  labels:
    app: socketio
  annotations:
    com.idbmobile.conduit: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socketio
  template:
    metadata:
      labels:
        app: socketio
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - socketio
                topologyKey: kubernetes.io/hostname
      containers:
        - name: socketio
          image: eu.gcr.io/idb-mobile/common.socketio:0.1.3
          ports:
            - containerPort: 50051
          env:
            - name: NODE_ENV
              value: "staging"
            - name: APP_PORT
              value: "50051"
            - name: APP_NAME
              value: common/socketio-staging
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.2.0
          ports:
            - containerPort: 5775
              protocol: UDP
              name: zipkin
            - containerPort: 6831
              protocol: UDP
              name: compact
            - containerPort: 6832
              protocol: UDP
              name: binary
            - containerPort: 5778
              name: config
          env:
            - name: COLLECTOR_HOST_PORT
              value: "jaeger-collector.tracing.svc.cluster.local:14267"
